// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="assets/css/animate.min.css"></link>
        <link rel="stylesheet" href="assets/css/swiper-bundle.min.css"></link>
        <link rel="stylesheet" href="assets/css/scrollCue.min.css"></link>
        <link rel="stylesheet" href="assets/css/remixicon.css"></link>
        <link rel="stylesheet" href="assets/css/style.css"></link>
        <link rel="stylesheet" href="assets/css/responsive.css"></link>
        <link rel="icon" type="image/png" href="assets/images/favicon.png"></link>
      </head>
        
        <body>
        {children}
      </body>
    </html>
  );
}

